docs/aca/10-aca-iac-bicep/index.md
I just love Github Copilot. Almost all of the changes here were suggested by Copilot based on rest of the workshop I guess, but the important thing is, this is what I wanted to improve and Copilot was spot on for each of its suggestion.
I would have easily spent additional 30 mins or so to do this same change without copilot. Its a real life example of how Copilot is helping with developer productivity.
I just love it ❤️
=> chore: Module 10 ux consistency

docs/aca/01-deploy-api-to-aca/index.md, docs/aca/02-aca-comm/Create.cshtml.cs, docs/aca/02-aca-comm/Edit.cshtml.cs, docs/aca/02-aca-comm/Index.cshtml.cs, docs/aca/02-aca-comm/Tasks.Index.cshtml.cs, docs/aca/02-aca-comm/TasksModel.cs, docs/aca/02-aca-comm/index.md
This one was a bit rough... lots of code files missing using statements.
=> Crv module2

docs/aca/01-deploy-api-to-aca/index.md, docs/aca/02-aca-comm/Create.cshtml.cs, docs/aca/02-aca-comm/Edit.cshtml.cs, docs/aca/02-aca-comm/Index.cshtml.cs, docs/aca/02-aca-comm/Tasks.Index.cshtml.cs, docs/aca/02-aca-comm/TasksModel.cs, docs/aca/02-aca-comm/index.md, docs/aca/03-aca-dapr-integration/index.md
Be sure to merge module2 before this one. Only unique changes should be to docs/aca/03-aca-dapr-integration/index.md
=> Crv module3

docs/aca/04-aca-dapr-stateapi/index.md
=> fix: local run missing link waring #73

aca-components/containerapps-pubsub-svcbus.yaml, docs/aca/05-aca-dapr-pubsubapi/index.md
Fixes remaining, old references.
=> Replace remaining tasks-processor-subscription with sbts-tasks-processor

.gitignore, .markdownlint.json, docs/aca/13-appendix/03-variables.md, docs/aca/13-appendix/Set-Variables.ps1
Sets and restores variables in between consoles or workshop sessions
=> Set and restore variables

docs/aca/13-appendix/Set-Variables.ps1
Minor tweak that makes the file cleaner and provides feedback to the user as to how many variables were saved.
=> Make the set-variables file just a bit cleaner

docs/aca/13-appendix/Set-Variables.ps1
Set variables.ps1 script to print applied variables
=> Set-Variables Changes

docs/aca/01-deploy-api-to-aca/index.md, docs/aca/02-aca-comm/index.md, docs/aca/03-aca-dapr-integration/index.md, docs/aca/04-aca-dapr-stateapi/index.md, docs/aca/05-aca-dapr-pubsubapi/index.md, docs/aca/13-appendix/03-variables.md
This PR improves:
- General usability by making the scripts easier to use.
- Formatting
- Consistent naming (`--resource-group` instead of `-g`, etc.)
- Added clarifying comments
=> Miscellaneous Module 1-5 Changes

docs/aca/01-deploy-api-to-aca/index.md, docs/aca/06-aca-dapr-bindingsapi/ExternalTasksProcessorController.cs, docs/aca/06-aca-dapr-bindingsapi/Update.ExternalTasksProcessorController.cs, docs/aca/06-aca-dapr-bindingsapi/containerapps-secretstore-kv.yaml, docs/aca/06-aca-dapr-bindingsapi/index.md
- Format, clarify, standardize Module 6
- Minor modification of Azure Subscription ID in Module 1 as part of the Module 6 work
=> Update Module 6

Makefile, mkdocs.yml
=> Pull latest MkDocs image & Fix MkDocs Dependency Issue

docs/aca/02-aca-comm/Create.cshtml.cs, docs/aca/02-aca-comm/Edit.cshtml.cs, docs/aca/02-aca-comm/Index.cshtml, docs/aca/02-aca-comm/Tasks.Index.cshtml, docs/aca/02-aca-comm/Tasks.Index.cshtml.cs, docs/aca/03-aca-dapr-integration/Create.cshtml.cs, docs/aca/03-aca-dapr-integration/Edit.cshtml.cs, docs/aca/03-aca-dapr-integration/Tasks.Index.cshtml.cs
=> Require Email to Prevent Crash

docs/aca/00-workshop-intro/4-prerequisites.md, docs/aca/01-deploy-api-to-aca/Program.cs, docs/aca/01-deploy-api-to-aca/global.json, docs/aca/01-deploy-api-to-aca/index.md, docs/aca/02-aca-comm/Program.cs, docs/aca/02-aca-comm/Tasks.Index.cshtml.cs, docs/aca/02-aca-comm/index.md, docs/aca/03-aca-dapr-integration/Frontend.Ui.csproj, docs/aca/03-aca-dapr-integration/Program.cs, docs/aca/03-aca-dapr-integration/index.md, docs/aca/04-aca-dapr-stateapi/Backend.Api.csproj, docs/aca/04-aca-dapr-stateapi/Program.cs, docs/aca/04-aca-dapr-stateapi/index.md, docs/aca/10-aca-iac-bicep/iac-bicep.md, docs/aca/13-appendix/Set-Variables.ps1, mkdocs.yml, snippets/persist-state.md, snippets/restore-variables.md
This PR restructures the module consistently with _Overview_, _Modules_, and _Review_ sections. Additionally, minor copy changes as well as externalization of files are part of this.
=> Restructure modules 1-4

docs/aca/03-aca-dapr-integration/index.md, docs/aca/04-aca-dapr-stateapi/index.md, snippets/restore-variables.md
- Clarifies section 3's modules a little better even. 
- Homogenizes variable restoration in modules 3 & 4 as compared to module 2.
- Correctly cases *Dapr*.
=> Minor section tweaking

docs/aca/00-workshop-intro/4-prerequisites.md, docs/aca/01-deploy-api-to-aca/index.md, docs/aca/02-aca-comm/index.md, docs/aca/03-aca-dapr-integration/Frontend.Ui.csproj, docs/aca/03-aca-dapr-integration/index.md, docs/aca/04-aca-dapr-stateapi/index.md, mkdocs.yml, snippets/containerize-app.md
Some minor tweaks and optimizations, improving customer experience.
=> Use dockerize app snippet, format, common target port

docs/aca/05-aca-dapr-pubsubapi/index.md
=> Narrow the managed identity scope to the servicebus topic

docs/aca/06-aca-dapr-bindingsapi/index.md
- Restructure module 6 to streamline it
=> Restructure module 6

docs/aca/08-aca-monitoring/Program-Backend.API.cs, docs/aca/08-aca-monitoring/index.md
- Fixes row highlighting
- Fixes incorrect `using` statement
=> Module 8 Fixes

docs/aca/09-aca-autoscale-keda/index.md
I had to increase the volume of and decrease the interval between messages to cause scaling to occur. I verified successful scale out and scale in.
=> Restructure module 9

docs/aca/00-workshop-intro/1-aca-core-components.md, docs/aca/00-workshop-intro/2-scenario-architecture.md, docs/aca/00-workshop-intro/4-prerequisites.md, docs/aca/00-workshop-intro/index.md, docs/aca/01-deploy-api-to-aca/index.md, docs/aca/02-aca-comm/index.md, docs/aca/03-aca-dapr-integration/index.md, docs/aca/04-aca-dapr-stateapi/index.md, docs/aca/05-aca-dapr-pubsubapi/index.md, docs/aca/06-aca-dapr-bindingsapi/index.md, docs/aca/07-aca-cron-bindings/index.md, docs/aca/08-aca-monitoring/index.md, docs/aca/09-aca-autoscale-keda/index.md, docs/aca/10-aca-iac-bicep/01-iac-bicep.md, docs/aca/10-aca-iac-bicep/02-ci-cd-git-action.md, docs/aca/10-aca-iac-bicep/03-ci-cd-azdo.md, docs/aca/10-aca-iac-bicep/index.md, docs/aca/11-aca-landing-zone/index.md, docs/aca/12-optimize-containers/index.md, docs/aca/29-about-the-authors/index.md, docs/aca/30-appendix/01-run-debug-dapr-app-vscode.md, docs/aca/30-appendix/02-github-local-codespaces.md, docs/aca/30-appendix/03-variables.md, docs/aca/30-appendix/04-troubleshooting.md, mkdocs.yml
* Added canonical URLs when missing and preserved when existing
* Renamed subfolders for consistency
No changes to content
=> updated structure for consistency and added canonical urls when missing
